### ISSUE TITLE
Octave for android crashes

### ISSUE THREAD

**Issue by davidluca3000** [corbinlc/octave4android#78] opened 2014-08-18 13:28 UTC
Hello Corbin,
I have same issue as other people and already tried several times, when I start Octave and after I click "Maybe later" I get for a short time "Terminal session is running" in notification area and then it just closes. I have a Sony Xperia ZR C5503 with Android 4.4.2, kernel version 3.4.0-perf-g32ce454.
Best regards,
David.

**Comment by corbinlc** [comment] 2015-01-09 06:15
Duplicate of #74 .  Please see update there.

**Closed by corbinlc** 2015-01-09 06:15 UTC
Labels: duplicate
